### ISSUE TITLE
`tox -e benchmark` ModuleNotFoundError: No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by oittaa** [hukkin/tomli#147] opened 2021-12-06 02:30 UTC
This might be an issue with `rtoml`, but the benchmark fails with the following error on MacOS:

```
ModuleNotFoundError: No module named 'setuptools_rust'
```

Workaround is to remove `rtoml` from benchmark/requirements.txt and install it after `setuptools-rust`.

```
$ git diff
diff --git a/benchmark/requirements.txt b/benchmark/requirements.txt
index 2433985..4bff435 100644
--- a/benchmark/requirements.txt
+++ b/benchmark/requirements.txt
@@ -6,4 +6,3 @@ pytomlpp
 toml
 tomlkit
 qtoml
-rtoml
diff --git a/pyproject.toml b/pyproject.toml
index 0aa803f..4c9d2fb 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -96,6 +96,8 @@ description = run the benchmark script against a local Tomli version
 deps =
     -r benchmark/requirements.txt
 commands =
+    pip3 install setuptools-rust
+    pip3 install rtoml
     python -c 'import datetime; print(datetime.date.today())'
     python --version
     python benchmark/run.py
```

**Comment by hukkin** [comment] 2021-12-06 09:11
I think the problem is that `rtoml` doesn't have its build dependencies specified (see [setuptools-rust docs](https://github.com/PyO3/setuptools-rust#pyprojecttoml)). We should probaby make a PR there.

I wonder why I never ran into this issue though... I don't seem to have `setuptools_rust` installed.

**Comment by oittaa** [comment] 2021-12-06 13:57
Do you have a computer with a x86 CPU? I ran into this with my M1 based Mac.

**Comment by hukkin** [comment] 2021-12-14 10:57
Oh yeah that must be why. I only have x86_64 CPUs.

Thanks for making a PR in rtoml! I'll close this issue here as it seems this will be resolved in rtoml. A temporary workaround can be found in the original post of this issue.

**Closed by hukkin** 2021-12-14 10:57 UTC
